name: example
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.11
  - pip=23.0.1
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - numpy
    - scipy
    - numba
    - h5py
    - torch
