name: torch
channels:
  - conda-forge
dependencies:
  - python=3.8.16
  - pip=23.0.1
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - numpy==1.22.4
    - scipy==1.10.1
    - numba==0.57.0
    - h5py==3.8.0
    - torch==2.0.1
